# Generated by Django 5.2.7 on 2025-11-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief, descriptive title for the tip', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('hvac', 'HVAC & Climate Control'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('exterior', 'Exterior & Roof'), ('interior', 'Interior'), ('appliances', 'Appliances'), ('yard', 'Yard & Landscaping'), ('safety', 'Safety'), ('seasonal', 'Seasonal'), ('pest_control', 'Pest Control'), ('general', 'General')], max_length=50)),
                ('content', models.TextField(help_text='The actual tip or advice')),
                ('location', models.CharField(help_text='City, region, or climate zone this tip applies to', max_length=200)),
                ('climate_zone', models.CharField(blank=True, help_text='Specific climate zone if applicable', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('moderation_notes', models.TextField(blank=True, help_text='Internal notes from moderators')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this tip as especially useful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_authored', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips_moderated', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='tips_upvoted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local Tip',
                'verbose_name_plural': 'Local Tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Moderators can hide inappropriate comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_comments', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tips.localtip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inaccurate', 'Inaccurate or Misleading Information'), ('unsafe', 'Unsafe Advice'), ('spam', 'Spam or Advertisement'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate Tip'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional details about the issue')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tips.localtip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='localtip',
            index=models.Index(fields=['status', '-created_at'], name='tips_localt_status_b08196_idx'),
        ),
        migrations.AddIndex(
            model_name='localtip',
            index=models.Index(fields=['location', 'category'], name='tips_localt_locatio_ab0646_idx'),
        ),
    ]
