# Generated by Django 5.2.7 on 2025-11-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtip',
            name='post_type',
            field=models.CharField(choices=[('tip', 'Expert Tip'), ('question', 'Question')], default='tip', help_text='Type of post: expert tip or homeowner question', max_length=20),
        ),
        migrations.AlterField(
            model_name='localtip',
            name='content',
            field=models.TextField(help_text='The tip content or question details'),
        ),
        migrations.AlterField(
            model_name='localtip',
            name='title',
            field=models.CharField(help_text='Brief, descriptive title for the tip or question', max_length=200),
        ),
    ]
