# Generated by Django 5.2.7 on 2025-11-24 02:50

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_localtip_post_type_alter_localtip_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Compelling title for the blog post', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('hvac', 'HVAC & Climate Control'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('exterior', 'Exterior & Roof'), ('interior', 'Interior'), ('appliances', 'Appliances'), ('yard', 'Yard & Landscaping'), ('safety', 'Safety'), ('seasonal', 'Seasonal'), ('pest_control', 'Pest Control'), ('diy', 'DIY Projects'), ('general', 'General')], help_text='Primary category for this article', max_length=50)),
                ('excerpt', models.TextField(help_text='Brief summary (shown in listings, max 500 characters)', max_length=500)),
                ('content', ckeditor.fields.RichTextField(help_text='Full article content with rich text formatting')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional featured image for the article', null=True, upload_to='blog_images/')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 characters)', max_length=160)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on blog homepage')),
                ('moderation_notes', models.TextField(blank=True, help_text='Internal notes from moderators')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(limit_choices_to={'is_verified_expert': True}, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts_moderated', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='blog_posts_upvoted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tips.blogpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='tips_blogpo_publish_737508_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status'], name='tips_blogpo_status_259de1_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category'], name='tips_blogpo_categor_a66cbc_idx'),
        ),
    ]
