# Generated by Django 5.2.7 on 2025-11-23 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_expert',
            field=models.BooleanField(default=False, help_text='Verified as having professional expertise (admin-approved)'),
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Your business or company name', max_length=200)),
                ('trade', models.CharField(choices=[('hvac', 'HVAC Technician'), ('plumbing', 'Plumber'), ('electrical', 'Electrician'), ('roofing', 'Roofing Specialist'), ('general_contractor', 'General Contractor'), ('landscaping', 'Landscaping/Lawn Care'), ('pest_control', 'Pest Control'), ('home_inspector', 'Home Inspector'), ('appliance_repair', 'Appliance Repair'), ('handyman', 'Handyman Services'), ('other', 'Other')], help_text='Your primary trade or specialty', max_length=50)),
                ('business_phone', models.CharField(help_text='Business phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('business_email', models.EmailField(help_text='Business email address', max_length=254)),
                ('street_address', models.CharField(help_text='Street address of your business', max_length=300)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State or province', max_length=50)),
                ('zip_code', models.CharField(help_text='ZIP or postal code', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid ZIP code (e.g., 12345 or 12345-6789)', regex='^\\d{5}(-\\d{4})?$')])),
                ('license_number', models.CharField(blank=True, help_text='Professional license number (if applicable)', max_length=100)),
                ('years_in_business', models.PositiveIntegerField(default=0, help_text='How many years have you been in business?')),
                ('insurance_verified', models.BooleanField(default=False, help_text='Has proof of insurance been verified by admin?')),
                ('website', models.URLField(blank=True, help_text='Your business website')),
                ('application_submitted', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_experts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert Profile',
                'verbose_name_plural': 'Expert Profiles',
                'ordering': ['-application_submitted'],
            },
        ),
    ]
