# Generated by Django 5.2.7 on 2025-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_verified_expert_expertprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Schedule customization: preferred_frequency, reminder_days_before, auto_reschedule'),
        ),
    ]
