# Generated by Django 5.2.7 on 2025-11-23 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the maintenance task (e.g., "Change HVAC Filter")', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('hvac', 'HVAC & Climate Control'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('exterior', 'Exterior & Roof'), ('interior', 'Interior'), ('appliances', 'Appliances'), ('yard', 'Yard & Landscaping'), ('safety', 'Safety Systems'), ('seasonal', 'Seasonal'), ('general', 'General Maintenance')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of what this task involves')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Twice per Year'), ('annual', 'Annually'), ('biennial', 'Every 2 Years'), ('as_needed', 'As Needed')], default='annual', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner - Easy DIY'), ('intermediate', 'Intermediate - Some Skills Required'), ('advanced', 'Advanced - Consider Professional'), ('professional', 'Professional Only')], default='beginner', max_length=20)),
                ('estimated_time', models.IntegerField(blank=True, help_text='Estimated time in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tools_required', models.TextField(blank=True, help_text='List of tools needed (one per line or comma-separated)')),
                ('step_by_step', models.TextField(blank=True, help_text='Step-by-step instructions for completing this task')),
                ('safety_notes', models.TextField(blank=True, help_text='Important safety considerations')),
                ('video_url', models.URLField(blank=True, help_text='Link to instructional video (YouTube, etc.)')),
                ('applies_to_old_homes', models.BooleanField(default=True, help_text='Relevant for homes older than 20 years')),
                ('applies_to_new_homes', models.BooleanField(default=True, help_text='Relevant for newer homes')),
                ('requires_basement', models.BooleanField(default=False)),
                ('requires_attic', models.BooleanField(default=False)),
                ('requires_hvac', models.BooleanField(default=False)),
                ('requires_septic', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this task should appear in recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Task',
                'verbose_name_plural': 'Maintenance Tasks',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='When this task should be performed')),
                ('completed_date', models.DateField(blank=True, help_text='When this task was actually completed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about this specific instance of the task')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost if professional service was used', max_digits=10, null=True)),
                ('performed_by', models.CharField(blank=True, help_text='Who performed the task (DIY, professional name, etc.)', max_length=200)),
                ('recurs', models.BooleanField(default=True, help_text='Whether this task should automatically reschedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='homes.home')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.maintenancetask')),
            ],
            options={
                'ordering': ['scheduled_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('actual_time', models.IntegerField(blank=True, help_text='Actual time spent in minutes', null=True)),
                ('feedback', models.TextField(blank=True, help_text='User feedback about the task (difficulty, tips, etc.)')),
                ('rating', models.IntegerField(blank=True, help_text='How helpful were the instructions? (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='maintenance.schedule')),
            ],
            options={
                'ordering': ['-completed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['home', 'scheduled_date'], name='maintenance_home_id_11ee62_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status', 'scheduled_date'], name='maintenance_status_b40001_idx'),
        ),
    ]
