# Generated by Django 5.2.7 on 2025-11-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_home_city_home_state_home_zip_code_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-scheduled_date']},
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='maintenance_status_b40001_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='recurs',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='task',
        ),
        migrations.AddField(
            model_name='schedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this schedule was marked complete', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this schedule has been completed'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tasks',
            field=models.ManyToManyField(help_text='Tasks included in this schedule', related_name='schedules', to='maintenance.maintenancetask'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='homes.home'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this maintenance schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_date',
            field=models.DateField(help_text='When these tasks should be performed'),
        ),
    ]
