# Generated by Django 5.2.7 on 2025-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='seasonal_priority',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('any', 'Any Season')], default='any', help_text='Optimal season for this task (e.g., HVAC checks in spring/fall)', max_length=20),
        ),
    ]
