# Generated by Django 5.2.7 on 2025-11-27 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancetask_seasonal_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('next_scheduled_date', models.DateField(blank=True, help_text='When this task was automatically rescheduled', null=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='maintenance.schedule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_completions', to='maintenance.maintenancetask')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('schedule', 'task')},
            },
        ),
    ]
