# Generated by Django 5.2.7 on 2025-11-27 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_scheduletaskcompletion'),
    ]

    operations = [
    ]
