# Generated by Django 5.2.7 on 2025-11-27 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20251126_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTaskCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_instructions', models.TextField(blank=True, help_text='User-customized instructions (overrides default task instructions)')),
                ('custom_notes', models.TextField(blank=True, help_text='Personal notes about this task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_customizations', to='maintenance.schedule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='maintenance.maintenancetask')),
            ],
            options={
                'ordering': ['schedule', 'task'],
                'unique_together': {('schedule', 'task')},
            },
        ),
    ]
