# Generated by Django 5.2.7 on 2025-11-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_scheduletaskcustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletaskcustomization',
            name='custom_description',
            field=models.TextField(blank=True, help_text='User-customized description (overrides default task description)'),
        ),
    ]
