# Generated by Django 5.2.7 on 2025-11-23 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A nickname for this home (e.g., "Main House", "Rental Property")', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Physical address of the property')),
                ('year_built', models.IntegerField(help_text='Year the home was constructed', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('construction_type', models.CharField(choices=[('wood_frame', 'Wood Frame'), ('brick', 'Brick'), ('concrete', 'Concrete'), ('steel_frame', 'Steel Frame'), ('mixed', 'Mixed Materials')], default='wood_frame', max_length=50)),
                ('climate_zone', models.CharField(choices=[('tropical', 'Tropical'), ('dry', 'Dry/Arid'), ('temperate', 'Temperate'), ('continental', 'Continental'), ('polar', 'Polar'), ('midwest', 'Midwestern U.S.'), ('northeast', 'Northeastern U.S.'), ('southeast', 'Southeastern U.S.'), ('southwest', 'Southwestern U.S.'), ('northwest', 'Northwestern U.S.')], default='temperate', max_length=50)),
                ('square_footage', models.IntegerField(blank=True, help_text='Total square footage of the home', null=True, validators=[django.core.validators.MinValueValidator(100)])),
                ('num_bedrooms', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('num_bathrooms', models.DecimalField(decimal_places=1, default=2.0, help_text='Number of bathrooms (0.5 = half bath)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('has_basement', models.BooleanField(default=False)),
                ('has_attic', models.BooleanField(default=False)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_hvac', models.BooleanField(default=True, help_text='Central heating/cooling')),
                ('has_septic', models.BooleanField(default=False, help_text='Septic system vs municipal sewer')),
                ('has_well', models.BooleanField(default=False, help_text='Well water vs municipal water')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the property')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The homeowner who manages this property', on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(choices=[('hvac', 'HVAC System'), ('water_heater', 'Water Heater'), ('furnace', 'Furnace'), ('ac_unit', 'Air Conditioning Unit'), ('refrigerator', 'Refrigerator'), ('washer', 'Washing Machine'), ('dryer', 'Dryer'), ('dishwasher', 'Dishwasher'), ('oven', 'Oven/Stove'), ('sump_pump', 'Sump Pump'), ('garage_door', 'Garage Door Opener'), ('other', 'Other')], max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=200)),
                ('year_installed', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='homes.home')),
            ],
            options={
                'ordering': ['appliance_type', '-year_installed'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('hvac', 'HVAC Technician'), ('roofer', 'Roofer'), ('carpenter', 'Carpenter'), ('landscaper', 'Landscaper'), ('painter', 'Painter'), ('handyman', 'Handyman'), ('pest_control', 'Pest Control'), ('appliance_repair', 'Appliance Repair'), ('general_contractor', 'General Contractor'), ('other', 'Other')], max_length=50)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about service quality, pricing, availability, etc.')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by community moderators')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='homes.home')),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['category', 'company_name'],
            },
        ),
    ]
