# Generated by Django 5.2.7 on 2025-11-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.CharField(blank=True, help_text='City where the property is located', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province where the property is located', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='zip_code',
            field=models.CharField(blank=True, help_text='ZIP or postal code', max_length=10),
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.TextField(blank=True, help_text='Street address of the property'),
        ),
    ]
