# Generated by Django 5.2.7 on 2025-11-26 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_home_city_home_state_home_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='energy_rating',
            field=models.CharField(blank=True, help_text='Energy Star rating or efficiency class (e.g., A+, Energy Star)', max_length=10),
        ),
        migrations.AddField(
            model_name='appliance',
            name='last_service_date',
            field=models.DateField(blank=True, help_text='Date of last professional service or maintenance', null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number for warranty and service records', max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='hvac_age',
            field=models.IntegerField(blank=True, help_text='Age of the HVAC system in years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='home',
            name='hvac_type',
            field=models.CharField(blank=True, choices=[('central_ac', 'Central Air Conditioning'), ('heat_pump', 'Heat Pump'), ('furnace_ac', 'Furnace + AC'), ('boiler', 'Boiler System'), ('ductless_mini_split', 'Ductless Mini-Split'), ('window_units', 'Window Units'), ('none', 'No HVAC')], default='', help_text='Type of HVAC system', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='roof_age',
            field=models.IntegerField(blank=True, help_text='Age of the roof in years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='home',
            name='roof_type',
            field=models.CharField(blank=True, choices=[('asphalt_shingle', 'Asphalt Shingle'), ('metal', 'Metal'), ('tile', 'Tile (Clay/Concrete)'), ('slate', 'Slate'), ('wood_shake', 'Wood Shake/Shingle'), ('flat', 'Flat/Low-Slope'), ('other', 'Other')], default='', help_text='Type of roofing material', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='siding_material',
            field=models.CharField(blank=True, choices=[('vinyl', 'Vinyl'), ('wood', 'Wood'), ('brick', 'Brick'), ('stucco', 'Stucco'), ('fiber_cement', 'Fiber Cement'), ('metal', 'Metal'), ('stone', 'Stone/Stone Veneer'), ('mixed', 'Mixed Materials')], default='', help_text='Primary siding/exterior material', max_length=50),
        ),
    ]
