# Generated by Django 5.2.7 on 2025-11-26 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_appliance_energy_rating_appliance_last_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='acreage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total acreage of the property', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='home',
            name='location_type',
            field=models.CharField(blank=True, choices=[('rural', 'Rural'), ('suburban', 'Suburban'), ('urban', 'Urban')], default='', help_text='Rural, suburban, or urban setting', max_length=20),
        ),
    ]
