# Generated by Django 5.2.7 on 2025-11-26 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_home_acreage_home_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='acreage',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Total acreage of the property', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='location_type',
            field=models.CharField(choices=[('rural', 'Rural'), ('suburban', 'Suburban'), ('urban', 'Urban')], default='suburban', help_text='Rural, suburban, or urban setting', max_length=20),
        ),
    ]
