# Generated by Django 5.2.7 on 2025-11-26 23:53

from django.db import migrations
from decimal import Decimal


def populate_acreage_and_location(apps, schema_editor):
    """
    Populate existing homes with varied dummy data for acreage and location_type.
    """
    Home = apps.get_model('homes', 'Home')
    
    # Varied dummy data patterns
    acreage_values = [Decimal('0.15'), Decimal('0.25'), Decimal('0.33'), Decimal('0.50'), 
                      Decimal('1.00'), Decimal('2.50'), Decimal('5.00'), Decimal('10.00')]
    location_types = ['urban', 'suburban', 'suburban', 'suburban', 'rural', 'rural']
    
    homes = Home.objects.all()
    for index, home in enumerate(homes):
        # Assign varied values based on index to ensure diversity
        home.acreage = acreage_values[index % len(acreage_values)]
        home.location_type = location_types[index % len(location_types)]
        home.save()


def reverse_populate(apps, schema_editor):
    """
    Reverse migration - set fields back to null/empty.
    """
    Home = apps.get_model('homes', 'Home')
    Home.objects.all().update(acreage=None, location_type='')


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_make_acreage_location_required'),
    ]

    operations = [
        migrations.RunPython(populate_acreage_and_location, reverse_populate),
    ]
