# Generated by Django 5.2.7 on 2025-11-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_populate_acreage_location_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='driveway_type',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('paved', 'Paved (asphalt/concrete)'), ('gravel', 'Gravel'), ('dirt', 'Dirt/unpaved')], default='', help_text='Type of driveway surface', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='has_barn_outbuilding',
            field=models.BooleanField(default=False, help_text='Barn or large outbuilding'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_battery_bank',
            field=models.BooleanField(default=False, help_text='Battery storage system'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_chainsaw',
            field=models.BooleanField(default=False, help_text='Chainsaw or power tools'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_composting_toilet',
            field=models.BooleanField(default=False, help_text='Composting toilet system'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_farm_implements',
            field=models.BooleanField(default=False, help_text='Plow, disc, or farming implements'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_fencing',
            field=models.BooleanField(default=False, help_text='Property has fencing'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_fruit_trees',
            field=models.BooleanField(default=False, help_text='Fruit trees or orchard'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_garden_beds',
            field=models.BooleanField(default=False, help_text='Garden beds or vegetable garden'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_generator',
            field=models.BooleanField(default=False, help_text='Backup generator'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_greenhouse',
            field=models.BooleanField(default=False, help_text='Greenhouse or cold frame'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_irrigation_system',
            field=models.BooleanField(default=False, help_text='Automated irrigation system'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_pasture',
            field=models.BooleanField(default=False, help_text='Pasture land for livestock'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_rainwater_collection',
            field=models.BooleanField(default=False, help_text='Rainwater harvesting/cistern'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_riding_mower',
            field=models.BooleanField(default=False, help_text='Riding lawn mower'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_solar_panels',
            field=models.BooleanField(default=False, help_text='Solar energy system'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_sump_pump',
            field=models.BooleanField(default=False, help_text='Sump pump in basement/crawlspace'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_tractor',
            field=models.BooleanField(default=False, help_text='Tractor or heavy equipment'),
        ),
        migrations.AddField(
            model_name='home',
            name='has_wood_stove',
            field=models.BooleanField(default=False, help_text='Wood stove or fireplace insert'),
        ),
        migrations.AddField(
            model_name='home',
            name='water_heater_type',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('tank', 'Tank Water Heater'), ('tankless', 'Tankless Water Heater'), ('hybrid', 'Hybrid Heat Pump'), ('solar', 'Solar Water Heater')], default='', help_text='Type of water heater', max_length=20),
        ),
    ]
