# Generated by Django 5.2.7 on 2025-11-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Optional featured image for the post', null=True, upload_to='post_images/'),
        ),
    ]
